### ISSUE TITLE
Module doesn't work correctly on CE 1.9.2

### ISSUE THREAD

**Issue by robbieaverill** [robbieaverill/magento-attribute-option-order-fix#1]
Steps to reproduce:
1. Install vanilla 1.9.2
2. Install sample data pack
3. Navigate to a configurable product page
4. Observe sizes are listed in incorrect order
5. Apply this module
6. Refresh - observe stack trace: `Fatal error: Call to a member function setProductFilter() on a non-object in app\code\core\Mage\Catalog\Model\Product\Type\Configurable.php on line 301`
7. Debugging ( `var_dump(get_class(...))`) in app/code/core/Mage/Catalog/Model/Product/Type/Configurable.php of line 300 returns false from the resource model rewrite

Expected result: (`RobbieAverill_AttributeFix_Model_Resource_Product_Type_Configurable_Attribute_Collection`)

Actual result:
`boolean false`

**Comment by robbieaverill** [comment]
Has just come down to spaces around the class name in the configuration XML file. Validated with flat tables and EAV.

**Comment by robbieaverill** [comment]
![image](https://cloud.githubusercontent.com/assets/5170590/9420841/971d8f3c-48be-11e5-8391-26b6a9d4a1a6.png)

**Comment by aed0nis** [comment]
This really pisses me off that this was the solution. Thanks for figuring it out.
