### ISSUE TITLE
Bug causes custom product pricing settings to be cleared after using Quick Create

### ISSUE THREAD

**Issue by andrewcbi** [robbieaverill/magento-attribute-option-order-fix#11]
Hi Robbie,
Thanks for sharing this patch.

I have installed this patch (latest version off github) on a local test server with 1.9.2.2 and have found an issue when the patch is enabled:
- on load the existing attribute pricing loads ok (for example the price difference of colours).
- if I use the Quick Create section - on clicking the Quick Create button it saves the new item but clears (leaves the field empty) the pricing variation (both percentage type and fixed type) for all existing attributes. The Fixed / Percentage drop downs are reverted to "Fixed".
- On save of the configurable product (to keep the simple product association) the attribute price values are lost and have to be re-entered.
- Have removed the patch and normal function for Quick Create is restored.

Hope this makes sense.

**Comment by robbieaverill** [comment]
Hi @andrewcbi 

Thanks for reporting - I'll evaluate this in the next day or two.

Cheers,
Robbie

**Comment by andrewcbi** [comment]
Thanks Robbie, much appreciated.

**Comment by robbieaverill** [comment]
Hi @andrewcbi

I've done some investigation:

> if I use the Quick Create section - on clicking the Quick Create button it saves the new item but clears (leaves the field empty) the pricing variation (both percentage type and fixed type) for all existing attributes. The Fixed / Percentage drop downs are reverted to "Fixed".

The configurable attribute dropdowns under "Quick simple product creation" do revert to blank after clicking "Quick Create", however I was able to reproduce this on a vanilla Magento 1.9.2.1 environment, so it doesn't appear to be related to this patch but rather expected behaviour (whilst it is annoying, I agree with you).

> On save of the configurable product (to keep the simple product association) the attribute price values are lost and have to be re-entered.

This doesn't occur for me. My price values persist.

> Have removed the patch and normal function for Quick Create is restored.

Is it possible that the process of removing the patch (probably clearing your cache, maybe restarting the web server, etc) may have made it appear to be resolved? Can you re-apply the patch and un-apply it a few more times to confirm?

Looking forward to hearing back.

Thanks,
Robbie

**Comment by andrewcbi** [comment]
Hi Robbie, thanks for the reply, I'll do some further testing this weekend and let you know the result.

**Comment by andrewcbi** [comment]
Hi @robbieaverill 
I've added the latest version of the code including bug fix #12 to Magneto CE 1.9.2.2

On front end all works well but Quick Create is still affected.

Using "Quick Simple Product Creation"

1) Entered the following:
- Do not auto generate (manually set name and SKU).
- Status: Enabled.
- Visibility: Not Visible Individually
- Finish: (set colour code)
- Qty: 1
- Stock Availability: In Stock

2) Press Quick Create button.

Item is added in correct order to the Super Product Attributes Configuration.

All price values are wiped clean but for new one added.

3) I choose not to save the main Configurable Product so not to apply the blank values...

4) Because I do not save the main Configurable Product the values for the other existing super product attributes configuration are still there. However the new product I just created using Quick Create is not linked to the Configurable Product.

5) I go and delete this new quick create product to try the process again.

6) I use Quick Simple Product Creation (same information as step 1).

7) I press the Quick Create Button.

8) Same as step 2 happens.

9) This time I choose to save the Configurable Product. (Save and Continue Edit).

10) The Super Product attributes configuration - all price options remain empty but for the one just generated. (the association with the Configurable Product is retained).

11) For some reason at this point pricing is not affected in the list of products shown in the admin (the price has not updated in the Price Column to reflect the empty percentages above.

12) However if you check the front end of the site - without the percentages in the back end the price differences no longer reflect in that attribute's selection box. The only remaining price difference is the one quick create product that was created in step 9. Confirming that data is wiped using the process above.

13) Disabled the addon again and cache cleared - confirm issue no longer occurs.

Hope the above helps.

**Comment by robbieaverill** [comment]
Hi @andrewcbi 

Thanks for the detailed steps. I must not have understood your problem entirely. I'll take a look in the next few days and try and get to the bottom of this.

Thanks,
Robbie

**Comment by robbieaverill** [comment]
Hi @andrewcbi 

Thanks for the details information. I have reproduced your issue. My problem was that I wasn't applying specific pricing per option.

I can now see that with this module active, the existing (saved) pricing fields for each attribute option are cleared after the AJAX request completes to add the new simple product.

So far it appears to me that by not saving the configurable after creating the simple product, the simple product is not associated to the configurable - this appears to be core Magento behaviour.

Will investigate.

Cheers,
Robbie

**Comment by robbieaverill** [comment]
Hi @andrewcbi 

Thanks for your patience. It appears to come down to a casting issue on the `value_index` for the attribute option.

I've pushed a fix (see pull request #15).

Please give it a try and let me know how it goes for you.

Thanks,
Robbie

**Comment by andrewcbi** [comment]
Thank you @robbieaverill , have tested this and can confirm this resolves the issue.

**Comment by robbieaverill** [comment]
Great! Glad we got to the bottom of it.

Thanks!
Robbie
