### ISSUE TITLE
PHP errror

### ISSUE THREAD

**Issue by aziwaan** [robbieaverill/magento-attribute-option-order-fix#16]
PHP Parse error:  syntax error, unexpected T_USE, expecting T_FUNCTION 

.modman/magento-attribute-option-order-fix/app/code/local/RobbieAverill/AttributeFix/Model/Resource/Product/Type/Configurable/Attribute/Collection.php on line 16

PHP version 5.3

Is there an easy fix to get this working on PHP 5.3?

**Comment by robbieaverill** [comment]
Hi,

This module requires PHP 5.4 or above. If you need a version that allows
5.3 please use an older version of this repo, check the reader changes for
where it was deprecated.

**Comment by robbieaverill** [comment]
@aziwaan Try using [tag `1.0.1`](https://github.com/robbieaverill/magento-attribute-option-order-fix/tree/1.0.1) - you won't have some of the more recent bug fixes, but it should work for the majority of applications excluding configurable swatches. Let me know if it works and if it does I'll push a `php5.3` tag against that version for future clarity.
