### ISSUE TITLE
Would you be able to shoot in a merge/pull here? https://github.com/OpenMage/magento-lts

### ISSUE THREAD

**Issue by seansan** [robbieaverill/magento-attribute-option-order-fix#17]
Would you be able to shoot in a merge/pull here? https://github.com/OpenMage/magento-lts

Or was it fixed already?

**Comment by robbieaverill** [comment]
I wasn't aware that there was such a fork open! I haven't had a chance to take a look at whether this issue is fixed in code yet, but I imagine that checking the issue tracker would be useful. Originally when it was acknowledged it was said to be fixed in the upcoming patch release (some time ago)

**Comment by seansan** [comment]
maybe double check

**Comment by robbieaverill** [comment]
@seansan this issue looks like it may have been resolved with the 1.9.3.0 release - the release notes say "Configurable products are now sorted by attribute, not by product ID." - waiting on confirmation from the bug report. I haven't tested it myself yet.

**Comment by robbieaverill** [comment]
I've just had a quick check against vanilla 1.9.3.2 and it looks like:

* Category pages are ordering by attribute ID (still broken)
* Product pages are ordering by attribute relevance (correct)

In this case this patch module probably needs to be tweaked for v1.9.3*, but will still need some logic in place to fix the category page order.
